replicaCount: 5

image:
  repository: timilsinamadhav/crawler-proxy-telemetry
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Proxy configuration
proxy:
  url: "http://65.108.203.37:18080"
  vendors:
    - name: vendor-a
      weight: 30
    - name: vendor-b
      weight: 40
    - name: vendor-c
      weight: 30

# Crawler configuration
crawler:
  # Target domains to crawl
  targets:
    - "httpbin.org"
    - "jsonplaceholder.typicode.com"
    - "reqres.in"
    - "postman-echo.com"
    - "httpstat.us"
  # Request interval in seconds
  intervalSeconds: 10
  # Number of concurrent requests per pod
  concurrency: 3
  # Enable HTTP/2 support
  http2Enabled: true

# Monitoring configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s
