{{- if .Values.apiService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices-app.fullname" . }}-api
  labels:
    {{- include "microservices-app.apiService.labels" . | nindent 4 }}
spec:
  {{- if not .Values.apiService.autoscaling.enabled }}
  replicas: {{ .Values.apiService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservices-app.apiService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "microservices-app.apiService.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "microservices-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.apiService.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "microservices-app.apiService.image" . }}
          imagePullPolicy: {{ .Values.apiService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiService.service.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "microservices-app.fullname" . }}-config
                  key: NODE_ENV
            - name: PORT
              value: "{{ .Values.apiService.service.targetPort }}"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "microservices-app.fullname" . }}-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "microservices-app.fullname" . }}-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "microservices-app.fullname" . }}-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "microservices-app.fullname" . }}-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "microservices-app.fullname" . }}-secret
                  key: DB_PASSWORD
          {{- with .Values.apiService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.apiService.resources | nindent 12 }}
      {{- with .Values.apiService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.apiService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservices-app.fullname" . }}-api
  labels:
    {{- include "microservices-app.apiService.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservices-app.fullname" . }}-api
  minReplicas: {{ .Values.apiService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.apiService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apiService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
