{{- if .Values.frontendService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices-app.fullname" . }}-frontend
  labels:
    {{- include "microservices-app.frontendService.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontendService.autoscaling.enabled }}
  replicas: {{ .Values.frontendService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservices-app.frontendService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "microservices-app.frontendService.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "microservices-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.frontendService.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "microservices-app.frontendService.image" . }}
          imagePullPolicy: {{ .Values.frontendService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontendService.service.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "microservices-app.fullname" . }}-config
                  key: NODE_ENV
          {{- with .Values.frontendService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontendService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontendService.resources | nindent 12 }}
      {{- with .Values.frontendService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontendService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontendService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.frontendService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservices-app.fullname" . }}-frontend
  labels:
    {{- include "microservices-app.frontendService.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservices-app.fullname" . }}-frontend
  minReplicas: {{ .Values.frontendService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontendService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.frontendService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontendService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.frontendService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontendService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
